# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76097becdd0a36c01f9be924ae3757b454a80909c0e5fcf3c0ebd08c76d448b2385e5cb50d5baa55a080991e323e42a4b82da3312f401adfc76171b570ab6466

test:
  secret_key_base: 92775fb0af81d449668eddd2a984d00826923692d0dbc75b2397fa1009efe202a277c2ba7a9cf1aca60169d87a751b93eb43d22f78b4af1c9579948329d1cc7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
